// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trackster.Api.Data;

#nullable disable

namespace Trackster.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250710204907_AddingShowRecords")]
    partial class AddingShowRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Trackster.Api.Data.EpisodeRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeasonIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("SeasonIdentifier");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Trackster.Api.Data.EpisodeUserRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("EpisodeIdentifier");

                    b.HasIndex("UserIdentifier");

                    b.ToTable("EpisodeUserLinks");
                });

            modelBuilder.Entity("Trackster.Api.Data.MovieRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("TMDB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identifier");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Trackster.Api.Data.MovieUserRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovieIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("MovieIdentifier");

                    b.HasIndex("UserIdentifier");

                    b.ToTable("MovieUserLinks");
                });

            modelBuilder.Entity("Trackster.Api.Data.SeasonRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShowIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("ShowIdentifier");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Trackster.Api.Data.ShowRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("TMDB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identifier");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("Trackster.Api.Data.UserRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Trackster.Api.Data.EpisodeRecord", b =>
                {
                    b.HasOne("Trackster.Api.Data.SeasonRecord", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Trackster.Api.Data.EpisodeUserRecord", b =>
                {
                    b.HasOne("Trackster.Api.Data.EpisodeRecord", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trackster.Api.Data.UserRecord", "User")
                        .WithMany()
                        .HasForeignKey("UserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trackster.Api.Data.MovieUserRecord", b =>
                {
                    b.HasOne("Trackster.Api.Data.MovieRecord", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trackster.Api.Data.UserRecord", "User")
                        .WithMany()
                        .HasForeignKey("UserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trackster.Api.Data.SeasonRecord", b =>
                {
                    b.HasOne("Trackster.Api.Data.ShowRecord", "Show")
                        .WithMany()
                        .HasForeignKey("ShowIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });
#pragma warning restore 612, 618
        }
    }
}
