// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trackster.Api.Data;

#nullable disable

namespace Trackster.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250912140343_CreateWebhookTable")]
    partial class CreateWebhookTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Trackster.Api.Data.Records.EpisodeRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeasonIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("SeasonIdentifier");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Trackster.Api.Data.Records.EpisodeUserRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("EpisodeIdentifier");

                    b.HasIndex("UserIdentifier");

                    b.ToTable("EpisodeUserLinks");
                });

            modelBuilder.Entity("Trackster.Api.Data.Records.MovieRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<string>("Poster")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TMDB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identifier");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Trackster.Api.Data.Records.MovieUserRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovieIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("MovieIdentifier");

                    b.HasIndex("UserIdentifier");

                    b.ToTable("MovieUserLinks");
                });

            modelBuilder.Entity("Trackster.Api.Data.Records.SeasonRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShowIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("ShowIdentifier");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Trackster.Api.Data.Records.SessionRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeToLive")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("UserIdentifier");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Trackster.Api.Data.Records.ShowRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<string>("Poster")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TMDB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identifier");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("Trackster.Api.Data.Records.UserRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Trackster.Api.Data.Records.WebhookRecord", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("UserIdentifier");

                    b.ToTable("Webhooks");
                });

            modelBuilder.Entity("Trackster.Api.Data.Records.EpisodeRecord", b =>
                {
                    b.HasOne("Trackster.Api.Data.Records.SeasonRecord", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Trackster.Api.Data.Records.EpisodeUserRecord", b =>
                {
                    b.HasOne("Trackster.Api.Data.Records.EpisodeRecord", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trackster.Api.Data.Records.UserRecord", "User")
                        .WithMany()
                        .HasForeignKey("UserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trackster.Api.Data.Records.MovieUserRecord", b =>
                {
                    b.HasOne("Trackster.Api.Data.Records.MovieRecord", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trackster.Api.Data.Records.UserRecord", "User")
                        .WithMany()
                        .HasForeignKey("UserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trackster.Api.Data.Records.SeasonRecord", b =>
                {
                    b.HasOne("Trackster.Api.Data.Records.ShowRecord", "Show")
                        .WithMany()
                        .HasForeignKey("ShowIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Trackster.Api.Data.Records.SessionRecord", b =>
                {
                    b.HasOne("Trackster.Api.Data.Records.UserRecord", "User")
                        .WithMany()
                        .HasForeignKey("UserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trackster.Api.Data.Records.WebhookRecord", b =>
                {
                    b.HasOne("Trackster.Api.Data.Records.UserRecord", "User")
                        .WithMany()
                        .HasForeignKey("UserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
