services:
    trackster:
        image: citr0s/trackster
        ports:
            - '83:80'
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
        volumes:
            - ./assets:/web-api/app/assets
